ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:21.0.1
# hadolint ignore=DL3006
FROM ${BUILD_FROM}

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup base
ARG BUILD_ARCH=amd64
ARG TAILSCALE_VERSION="v1.102.2"
ARG HA_CLI_VERSION="5.2.0"
RUN \
    apk add --no-cache \
        bash-completion=2.17.0-r1 \
        bind-tools=9.20.26-r0 \
        dnsmasq=2.92_p2-r0 \
        ethtool=7.0-r0 \
        ipcalc=1.0.3-r1 \
        iproute2=7.0.0-r0 \
        iptables=1.8.13-r0 \
        nginx=1.30.4-r1 \
        coreutils=9.11-r0 \
        networkmanager=1.52.2-r0 \
        inotify-tools=4.23.9.0-r0 \
    \
    && ln -sf /sbin/xtables-nft-multi /sbin/ip6tables \
    && ln -sf /sbin/xtables-nft-multi /sbin/iptables \
    \
    && rm -f -r \
        /usr/lib/NetworkManager/dispatcher.d \
    \
    && if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi \
    && if [ "${BUILD_ARCH}" = "amd64" ]; then ARCH="amd64"; fi \
    \
    && curl -L -s \
        "https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_VERSION#v}_${ARCH}.tgz" \
        | tar zxvf - -C /opt/ --strip-components 1 \
    \
    && rm -f -r \
        /opt/systemd \
    \
    && curl -L -s -o /usr/bin/ha \
        "https://github.com/home-assistant/cli/releases/download/${HA_CLI_VERSION}/ha_${BUILD_ARCH}" \
    && chmod a+x /usr/bin/ha \
    \
    && ha completion bash > /usr/share/bash-completion/completions/ha \
    && sed -i -e '1s#/bin/sh#/usr/bin/with-contenv-merge-bash#' /etc/passwd \
    && rm -f -r \
        /etc/motd

# Copy root filesystem
COPY rootfs /

HEALTHCHECK \
    CMD healthcheck

# Environment variables
ENV \
    # S6 Overlay stage 2 hook
    S6_STAGE2_HOOK=/etc/s6-overlay/scripts/stage2_hook.sh \
    # App log format
    LOG_FORMAT="{TIMESTAMP} {LEVEL}: {MESSAGE}" \
    LOG_TIMESTAMP="%Y/%m/%d %H:%M:%S"

# Build arguments
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION

# Labels
LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="Franck Nijhof <opensource@frenck.dev>" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="Home Assistant Community Apps" \
    org.opencontainers.image.authors="Franck Nijhof <opensource@frenck.dev>" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://frenck.dev/home-assistant-apps" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
